spring.application.name=studycast

spring.datasource.url=jdbc:postgresql://localhost:5432/studycast_db
spring.datasource.username=younghee
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis.type-aliases-package=com.younghee.studycast.dto
mybatis.type-handlers-package=com.younghee.studycast.config.typehandler

spring.profiles.include=secret

# Access Token 유효 시간
# 30분 = 1000 * 60 * 30
jwt.access-token-validity-ms=1800000

# Refresh Token 유효 시간
# 7일 = 1000 * 60 * 60 * 24 * 7
jwt.refresh-token-validity-ms=604800000

# 이메일 인증번호
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# 스터디방 정책
study-room.max-users-limit=4

# 토스페이먼츠
toss.payments.client-key=${TOSS_CLIENT_KEY:test_ck_placeholder}
toss.payments.secret-key=${TOSS_SECRET_KEY:test_sk_placeholder}

# 스터디방 대표 이미지 정책 추가
# 5MB 사용자 정의는 서비스에서 적용(초과 파일에 대한 안내 메세지)하므로, 크게 설정
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=7MB

study-room.image.max-size=5242880
study-room.image.upload-dir=uploads/rooms
study-room.image.allowed-types=image/jpeg, image/png

# LiveKit 설정
livekit.url=${LIVEKIT_URL}
livekit.api-key=${LIVEKIT_API_KEY}
livekit.api-secret=${LIVEKIT_API_SECRET}
livekit.token-ttl-minutes=120

# Kakao OAuth2 설정
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.scope=account_email,profile_nickname,profile_image

# Kakao Provider 설정
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# Google OAuth2 설정
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_post

# 프론트URL
app.frontend-url=http://localhost:5173
app.cookie-secure=false